# Generated by Django 6.0.3 on 2026-03-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Administrador'), ('conserje', 'Conserje'), ('residente', 'Residente')], default='residente', max_length=20),
        ),
    ]
