# Generated by Django 5.2.13 on 2026-04-09 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_common_spaces(apps, schema_editor):
    CommonSpace = apps.get_model('reservations', 'CommonSpace')

    CommonSpace.objects.update_or_create(
        code='pool',
        defaults={'name': 'Piscina', 'capacity': 6, 'is_active': True},
    )
    CommonSpace.objects.update_or_create(
        code='multi_use_room',
        defaults={'name': 'Sala multiuso', 'capacity': 30, 'is_active': True},
    )
    CommonSpace.objects.update_or_create(
        code='gym',
        defaults={'name': 'Gimnasio', 'capacity': 10, 'is_active': True},
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('pool', 'Piscina'), ('multi_use_room', 'Sala multiuso'), ('gym', 'Gimnasio')], max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=120)),
                ('requester_role', models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Administrador'), ('conserje', 'Conserje'), ('residente', 'Residente')], max_length=20)),
                ('reservation_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('common_space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservations.commonspace')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-reservation_date', '-start_time', '-id'),
            },
        ),
        migrations.RunPython(seed_common_spaces, migrations.RunPython.noop),
    ]
