# Generated by Django 6.0.3 on 2026-04-11 23:22

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CommonExpensePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('closed', 'Cerrado')], default='draft', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_periods', to='billing.condominium')),
            ],
            options={
                'ordering': ('-year', '-month', 'condominium_id'),
            },
        ),
        migrations.CreateModel(
            name='CondominiumService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('allocation_type', models.CharField(choices=[('fixed', 'Monto fijo'), ('percentage', 'Porcentaje'), ('per_unit', 'Por unidad')], default='fixed', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='billing.condominium')),
            ],
            options={
                'ordering': ('condominium_id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CommonExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.commonexpenseperiod')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_items', to='billing.condominiumservice')),
            ],
            options={
                'ordering': ('period_id', 'label'),
            },
        ),
        migrations.CreateModel(
            name='ResidentCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('late_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('partial', 'Parcial'), ('paid', 'Pagado'), ('overdue', 'Vencido')], default='pending', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='billing.commonexpenseperiod')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('transfer', 'Transferencia'), ('card', 'Tarjeta'), ('cash', 'Efectivo')], default='transfer', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=10)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('receipt_url', models.URLField(blank=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.residentcharge')),
            ],
            options={
                'ordering': ('-paid_at',),
            },
        ),
        migrations.CreateModel(
            name='ResidentChargeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_items', to='billing.residentcharge')),
            ],
            options={
                'ordering': ('charge_id', 'label'),
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='billing.condominium')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('condominium_id', 'number'),
            },
        ),
        migrations.AddField(
            model_name='residentcharge',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='billing.unit'),
        ),
        migrations.AddConstraint(
            model_name='commonexpenseperiod',
            constraint=models.UniqueConstraint(fields=('condominium', 'year', 'month'), name='unique_period_per_condominium'),
        ),
        migrations.AddConstraint(
            model_name='condominiumservice',
            constraint=models.UniqueConstraint(fields=('condominium', 'name'), name='unique_service_name_per_condominium'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('condominium', 'number'), name='unique_unit_per_condominium'),
        ),
        migrations.AddConstraint(
            model_name='residentcharge',
            constraint=models.UniqueConstraint(fields=('period', 'resident', 'unit'), name='unique_charge_per_resident_unit_period'),
        ),
    ]
