# Generated by Django 6.0.3 on 2026-04-11 23:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('closed', 'Cerrado'), ('generated', 'Generado')], default='open', max_length=20)),
                ('close_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='CommonExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('variable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('partial', 'Parcial'), ('paid', 'Pagado'), ('overdue', 'Vencido')], default='pending', max_length=12)),
                ('generated_at', models.DateField(default=django.utils.timezone.localdate)),
            ],
            options={
                'ordering': ('-generated_at',),
            },
        ),
        migrations.CreateModel(
            name='CommonSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('space_type', models.CharField(max_length=80)),
                ('block_duration', models.PositiveSmallIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('condominium_id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='payment_receipts/')),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateField(default=django.utils.timezone.localdate)),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-reservation_date', '-start_time'),
            },
        ),
        migrations.CreateModel(
            name='ResidentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_owner', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
        migrations.RemoveField(
            model_name='commonexpenseitem',
            name='period',
        ),
        migrations.RemoveField(
            model_name='commonexpenseitem',
            name='service',
        ),
        migrations.RemoveConstraint(
            model_name='commonexpenseperiod',
            name='unique_period_per_condominium',
        ),
        migrations.RemoveConstraint(
            model_name='condominiumservice',
            name='unique_service_name_per_condominium',
        ),
        migrations.RemoveConstraint(
            model_name='residentcharge',
            name='unique_charge_per_resident_unit_period',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='residentchargeitem',
            name='charge',
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-payment_date',)},
        ),
        migrations.RemoveField(
            model_name='condominium',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='receipt_url',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='review_notes',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='resident',
        ),
        migrations.AddField(
            model_name='condominium',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'Transferencia'), ('card', 'Tarjeta'), ('cash', 'Efectivo')], default='transfer', max_length=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.unit'),
        ),
        migrations.AddField(
            model_name='payment',
            name='validation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='proration_factor',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='condominium',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='unit',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingperiod',
            name='condominium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_periods', to='billing.condominium'),
        ),
        migrations.AddField(
            model_name='payment',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.billingperiod'),
        ),
        migrations.AddField(
            model_name='commonexpense',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_expenses', to='billing.billingperiod'),
        ),
        migrations.AddField(
            model_name='commonexpense',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_expenses', to='billing.unit'),
        ),
        migrations.AddField(
            model_name='commonspace',
            name='condominium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_spaces', to='billing.condominium'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='common_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='billing.commonspace'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='residentassignment',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_assignments', to='billing.unit'),
        ),
        migrations.AddField(
            model_name='residentassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CommonExpenseItem',
        ),
        migrations.RemoveField(
            model_name='commonexpenseperiod',
            name='condominium',
        ),
        migrations.RemoveField(
            model_name='condominiumservice',
            name='condominium',
        ),
        migrations.RemoveField(
            model_name='residentcharge',
            name='period',
        ),
        migrations.RemoveField(
            model_name='residentcharge',
            name='resident',
        ),
        migrations.RemoveField(
            model_name='residentcharge',
            name='unit',
        ),
        migrations.DeleteModel(
            name='ResidentChargeItem',
        ),
        migrations.AddConstraint(
            model_name='billingperiod',
            constraint=models.UniqueConstraint(fields=('condominium', 'start_date', 'end_date'), name='unique_billing_period_range_per_condo'),
        ),
        migrations.AddConstraint(
            model_name='commonexpense',
            constraint=models.UniqueConstraint(fields=('period', 'unit'), name='unique_common_expense_per_period_unit'),
        ),
        migrations.AddConstraint(
            model_name='commonspace',
            constraint=models.UniqueConstraint(fields=('condominium', 'name'), name='unique_common_space_per_condo'),
        ),
        migrations.DeleteModel(
            name='CondominiumService',
        ),
        migrations.DeleteModel(
            name='CommonExpensePeriod',
        ),
        migrations.DeleteModel(
            name='ResidentCharge',
        ),
    ]
