# Generated by Django 6.0.3 on 2026-05-02 16:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_reservation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_type', models.CharField(choices=[('agua', 'Agua'), ('luz', 'Luz'), ('gas', 'Gas'), ('calefaccion', 'Calefacción')], default='agua', max_length=20)),
                ('previous_reading', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('date_recorded', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(default='registrado', max_length=20)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='billing.unit')),
            ],
            options={
                'ordering': ('-date_recorded',),
            },
        ),
    ]
