# Generated by Django 6.0.3 on 2026-09-08 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_resident_memberships(apps, schema_editor):
    CondominiumMembership = apps.get_model('billing', 'CondominiumMembership')
    ResidentAssignment = apps.get_model('billing', 'ResidentAssignment')

    assignments = ResidentAssignment.objects.filter(is_active=True).select_related('unit')
    for assignment in assignments.iterator():
        CondominiumMembership.objects.update_or_create(
            user_id=assignment.user_id,
            condominium_id=assignment.unit.condominium_id,
            defaults={'role': 'residente', 'is_active': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_condominium_latitude_condominium_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CondominiumMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('conserje', 'Conserje'), ('residente', 'Residente')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='billing.condominium')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condominium_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('condominium_id', 'role', 'user_id'),
                'indexes': [models.Index(fields=['user', 'is_active'], name='membership_user_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'condominium'), name='unique_user_membership_per_condominium')],
            },
        ),
        migrations.RunPython(create_resident_memberships, migrations.RunPython.noop),
    ]
